In [2]:
"""
Data Vectorization using Count Vectorizer and Tfiff Transformer
Also trying its different parameters. 
Like max_df, min_df,  max_feateures.
"""

'\nData Vectorization using Count Vectorizer and Tfiff Transformer\nAlso trying its different parameters. \nLike max_df(max)\n'

In [ ]:
import re
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

In [3]:
corpus=open('C:\\Users\\Bilal\\Downloads\\Movies_TV.txt').read()

In [4]:
res=re.sub(r'Domain.*\n','',corpus)
#Removing first line, which is unnecessary.

In [5]:
data_list=res.split('\t')

In [6]:
##Q2

In [7]:
#Frequency
f_vect=CountVectorizer()
F=f_vect.fit_transform(data_list)
print(f_vect.vocabulary_)

{'movies_tv': 4503, 'pos': 5218, 'my': 4541, 'boy': 945, 'love': 4129, 'this': 6949, 'film': 2737, 'sometime': 6374, 'youngest': 7783, 'get': 3004, 'scared': 5983, 'of': 4747, 'captain': 1108, 'hook': 3391, 'the': 6913, 'story': 6569, 'be': 735, 'great': 3115, 'and': 426, 'think': 6944, 'little': 4067, 'can': 1091, 'really': 5529, 'connect': 1538, 'to': 7045, 'it': 3766, 'beautiful': 747, 'fun': 2930, 'music': 4534, 'as': 552, 'well': 7584, 'neu': 4617, 'on': 4785, 'disk': 2047, 'last': 3954, 'scene': 5995, 'episode': 2418, 'new': 4621, 'earth': 2228, 'miss': 4415, 'instead': 3663, 'cut': 1753, 'gory': 3074, 'from': 2913, 'what': 7595, 'appear': 489, 'texas': 6899, 'chainsaw': 1199, 'massacure': 4254, 'look': 4103, 'at': 584, 'dvd': 2206, 'menue': 4327, 'see': 6052, 'that': 6910, 'title': 7043, 'time': 7014, 'die': 1973, 'only': 4792, 'guess': 3151, 'manufacturer': 4221, 'insert': 3644, 'simularly': 6228, 'another': 456, 'movie': 4501, 'parent': 4970, 'warn': 7534, 'in': 3542, 'questio

In [8]:
vect=CountVectorizer(binary=True)

In [10]:
X=vect.fit_transform(data_list)

In [11]:
X.toarray()
#In binary form

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [9]:
##TfId

In [11]:
vect2=TfidfTransformer()

In [14]:
X.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [36]:
Y=vect2.fit_transform(X)

In [37]:
Y

<3001x7804 sparse matrix of type '<class 'numpy.float64'>'
	with 76549 stored elements in Compressed Sparse Row format>

In [38]:
Y.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [39]:
##Q3Keep ngrams..

In [45]:
vect3=CountVectorizer(ngram_range=(1,1))
unigram=vect3.fit_transform(data_list)
unigram.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [46]:
vect4=CountVectorizer(ngram_range=(1,2))
bigram=vect4.fit_transform(data_list)
bigram.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [47]:
vect5=CountVectorizer(ngram_range=(1,3))
trigram=vect5.fit_transform(data_list)
trigram.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [29]:
##Q4 Keep Minimum....
vect_last=CountVectorizer(max_df=100,min_df=10,max_features=1000)

In [31]:
K=vect_last.fit_transform(data_list)

In [40]:
print(vect_last.vocabulary_)

{'boy': 118, 'captain': 132, 'hook': 436, 'beautiful': 89, 'music': 577, 'neu': 586, 'disk': 252, 'last': 505, 'scene': 752, 'episode': 296, 'earth': 271, 'miss': 564, 'instead': 468, 'cut': 206, 'appear': 59, 'title': 903, 'die': 241, 'guess': 407, 'another': 54, 'parent': 623, 'question': 693, 'son': 814, 'cartoon': 136, 'wonderful': 980, 'animation': 51, 'excellent': 312, 'though': 893, 'may': 549, 'comment': 175, 'correct': 196, 'style': 851, 'hate': 417, 'point': 656, 'longer': 531, '50': 8, 'decade': 223, 'long': 530, 'course': 198, 'such': 852, 'depth': 234, 'each': 268, 'storyline': 843, 'aside': 65, 'delightful': 229, 'especially': 299, 'clean': 163, 'itself': 480, 'entertaining': 293, 'plot': 654, 'twist': 928, 'happen': 413, 'wand': 955, 'hand': 412, 'try': 923, 'prove': 686, 'without': 977, 'magical': 535, 'hold': 432, 'own': 618, 'version': 943, 'attempt': 68, 'form': 370, 'entertainment': 294, 'however': 442, 'part': 624, 'change': 147, 'mouse': 573, 'annoying': 53, 'enou

In [41]:
li=vect_last.get_feature_names()

In [44]:
len(li)

1000